project 'ZhaNiMei.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'ZhaNiMei' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZhaNiMei
   pod 'AFNetworking', '~> 3.1.0'
   pod 'MJExtension', '~> 3.0.13'
   pod 'SDWebImage', '~> 3.8.2'
   pod 'MJRefresh'
   pod 'DACircularProgress'
   pod 'SVProgressHUD'
end
